#!/bin/sh

git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

nvim --headless \
    -c 'lua require("config.plugins")' \
    -c 'autocmd User PackerComplete quitall' \
    -c 'PackerSync'

# give it some time to automatically install the LSPs
nvim --headless \
    -c 'sleep 10' \
    -c q

exit 0
