#!/bin/sh

git clone --filter=blob:none https://github.com/folke/lazy.nvim.git --branch=stable ~/.local/share/nvim/lazy/lazy.nvim

# give it some time to automatically install the LSPs
nvim --headless \
    -c 'sleep 10' \
    -c q

exit 0
